# Generated by Django 4.1.2 on 2022-10-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userscore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Userscore', models.IntegerField(max_length=5)),
                ('ExamsDone', models.CharField(max_length=255)),
            ],
        ),
    ]
